### PR TITLE
direct messages on home timeline (behind a setting)

### PR DESCRIPTION
**Pull request by ghost**
Addresses #23 

This is loosely based on the work from cyberspace with some additions and some additional specs.  This allows an individual user to receive direct messages into their home timeline.  It should be noted this setting only applies going forward so if I turn it on at 7pm only statuses received after 7pm will be delivered to my home timeline.

Here is what the setting looks like on the prefs page
screenshot 2019-02-21 17 03 21

Here is the preference working
screenshot 2019-02-21 18 16 31

### CODE REVIEW

**Comment by marek-lach** [comment]
This one would be great to have in the main Mastodon as well :-)

**Comment by clarfonthey** [comment]
This only affects new DMs, right? I assume that should be listed in the prefs like it is for boosts.

**Comment by ghost** [comment]
@clarfon right, this only affects new DMs.  The preference screenshot from above shows how its listed beside grouping boosts.  If you want to make it an on/off filter on the timeline I think this would have to be changed to always deliver the DMs to the home timeline in redis and then filter them out from the list based on the toggle.

**Comment by jhaye** [comment]
This is the last PR for the current milestone - could we have a rebase for this one too?

**Comment by ghost** [comment]
> This is the last PR for the current milestone - could we have a rebase for this one too?

Sure, give me a few

**Comment by ghost** [comment]
> This is the last PR for the current milestone - could we have a rebase for this one too?

Squashed and Rebased!

**Review by clarfonthey — APPROVED** [review]

**Review by 1011X — APPROVED** [review]

**Pull request merged**
