### PR TITLE
Merge latest upstream changes

### PR DESCRIPTION
**Pull request by clarfonthey**

### CODE REVIEW

**Review by jhaye — APPROVED** [review]
As I understand it, 2796146685ee97ed2aa177c29dcc45b126d19ef9 is everything where we diverge from upstream right now. It's not very much and merging looks safe to me, but I'd like to see the opinion of someone who is/was involved in mastodev first.

**Comment by clarfonthey** [comment]
@jhaye: Not quite. That commit is the merge commit which shows all of the changes from the version of upstream that's being merged, and the current master branch. There have been new changes since the latest upstream, but I'll wait to merge those until after this PR.

There aren't any major changes made; the only Florence-specific changes right now are the addition of the max-toot-chars setting, and… I think that's it.

**Comment by jhaye** [comment]
@clarfon Well then I would say we don't even need further reviewing, because merging changes that small shouldn't cause a problem.

**Review by mal0ki — APPROVED** [review]
After discussions on our Mattermost, I'm accepting all the changes.

**Review by 1011X — APPROVED** [review]

**Pull request merged**
