### PR TITLE
Instance only statuses

### PR DESCRIPTION
**Pull request by renatolond**
This is largely based on the glitch-soc implementation of instance-only to make it easier to incorporate back into glitch-soc.

This assumes that clients are still unaware of local-only statuses and to avoid leaking replies outside, if the local_only flag is missing, replies to local_only posts are posted as local_only.

As in the glitch-soc implementation, local_only statuses can only be seen by users that are logged in, logged out users do not see the local_only statuses in hashtag timelines or in the "take a look inside" one. local_only cannot be fetched by the other instances, even with the link. The default option is to federate the toot

* [ ]  Refactor "local_only" into something else to avoid confusion with "local", maybe "instance_only"

I originally thought about using different icons, but after discussion over at https://github.com/tootsuite/mastodon/pull/8427, it seems this would enough.

This fixes https://github.com/florence-social/mastodon-fork/issues/11

image
image
image
image
image
image

### CODE REVIEW

**Comment by clarfonthey** [comment]
It took me a bit to wrap my brain around the idea of why "local-only" can apply to all privacy settings, rather than just one, when I initially ran into this feature. Looking at the UI screenshots here still made it a bit weird to wrap my head around, but I think I finally understand it.

Perhaps what might make more sense to the UI is to add a checkbox on the dropdown for privacy settings instead of a separate button. Then, we'd change the privacy settings from public, unlisted, followers, and mentions to local, unlisted local, local followers, and local mentions.

This still isn't perfect, but I think that changing it to explicitly explain what all the privacy settings mean in a local-only context would be better than this UI right now.

This isn't necessarily a blocker to getting this feature out pre-1.0, but I feel like we may want to block solidifying the UI for a 1.0 release.

**Comment by renatolond** [comment]
Sorry, just noticed now that there was a conflict, merged master into the branch :)

> It took me a bit to wrap my brain around the idea of why "local-only" can apply to all privacy settings, rather than just one, when I initially ran into this feature. Looking at the UI screenshots here still made it a bit weird to wrap my head around, but I think I finally understand it.
> 
> Perhaps what might make more sense to the UI is to add a checkbox on the dropdown for privacy settings instead of a separate button. Then, we'd change the privacy settings from public, unlisted, followers, and mentions to local, unlisted local, local followers, and local mentions.
> 
> This still isn't perfect, but I think that changing it to explicitly explain what all the privacy settings mean in a local-only context would be better than this UI right now.
> 
> This isn't necessarily a blocker to getting this feature out pre-1.0, but I feel like we may want to block solidifying the UI for a 1.0 release.

My frontend skills are not the best, so I did what I could to to add this to vanilla in a way that made more-or-less sense, but I agree that the UI is not the best. This is similar to the UI in glitch-soc, in the sense that is an additional toggle on posting local or not, but it could reflect for instance on the texts of privacy, if this was somehow a toggle in the component that takes care of privacy as well.

**Comment by clarfonthey** [comment]
So I looked through the code and everything seems pretty okay to me. I'm not an expert on the code but it's been live on a bunch of instances by this point and works as expected.

I can make some kind of mockup for the UI I'm thinking of at some point before 1.0, but at least having what glitch-soc has is good enough for me. :+1:

**Review by clarfonthey — DISMISSED** [review]

**Comment by clarfonthey** [comment]
So, actually, I'll just sort-of share what I'm thinking here. Privacy settings currently:

* Public: Post to public timelines
* Unlisted: Do not post to public timelines
* Followers-only: Post to followers only
* Direct: Post to mentioned users only

With new UI, federated privacy settings would show:

* Public : Visible to everyone and posted on public timelines
* Unlisted: Visible to everyone, but not posted to public timelines
* Followers only: Visible to followers from any instance
* Direct: Visible to mentioned users, including those on other instances

With local-only:

* Local public: Only visible to (instance name) users; posted on local timeline
* Local unlisted: Only visible to (instance name) users; not posted to local timeline
* Local followers only: Only visible to followers on (instance name)
* Local direct: Only visible to mentioned users on (instance name)

**Comment by lawremipsum** [comment]
I like this, MSP Social uses it, and having it baked in would make Florence an easy choice to switch to.

**Comment by clarfonthey** [comment]
While the project is still small, we decided to rename the `master` branch to `main`. Unfortunately, you're going to have to reopen this PR on that branch.

**Pull request closed without merging**
