### PR TITLE
Update CHANGELOG

### PR DESCRIPTION
**Pull request by clarfonthey**
Thanks to @jhaye for putting this together.

This replaces the tootsuite changelog with our own, and redoes the version display to show a Florence-Mastodon version instead of a Mastodon version in the footer.

### CODE REVIEW

**Review by jhaye — DISMISSED** [review]

**Comment by mal0ki** [comment]
I want to hold off with approving these changes for a bit while we clear up some questions (posted on Mattermost)

**Comment by clarfonthey** [comment]
Updated changelog to show 2.9.0 instead of rc1, added mention of extra commits included, and added an optional suffix to the version display on the UI (currently empty, but could be used for glitch/etc. forks).

**Review by jhaye — DISMISSED** [review]

**Comment by mal0ki** [comment]
We need to update date, 
And add the submitted PRs, along with a "a lot of people made these, but these people submitted the PRs" (or wahtevs)

**Review by mal0ki — APPROVED** [review]
Discussions from Mattermost yielded change, and I approve those changes.

**Review by jhaye — APPROVED** [review]

**Pull request merged**
