### PR TITLE
i18n: 🇵🇱

### PR DESCRIPTION
**Pull request by mkljczk**
in fact, I made this PR mainly to announce that I'm gonna keep Florence-specific features translated to Polish, I know it's really small 😆

### CODE REVIEW

**Comment by clarfonthey** [comment]
Thank you so much! If you're interested I could also add you to the localisation team on florence-social so we can @ you whenever new changes are made.

**Comment by 1011X** [comment]
The test is failing because the updated file doesn't pass the normalization check.

To solve this, try running the following command:

    i18n-tasks normalize

If that doesn't work, try:

    build exec i18n-tasks normalize

**Comment by clarfonthey** [comment]
I believe that they did this through the web UI so I don't know if they'd be able to run that manually. I'll try to remember to add a commit in a bit to fix it.

**Comment by mkljczk** [comment]
I’ll do it in like an hour, I’m sorry but I only have limited internet access, I’ll just use my vps…

**Comment by mkljczk** [comment]
that was a long hour

**Comment by clarfonthey** [comment]
You're awesome. <3

**Review by clarfonthey — APPROVED** [review]

**Review by 1011X — APPROVED** [review]

**Review by jhaye — APPROVED** [review]

**Pull request merged**
