### PR TITLE
Instance only statuses

### LINKED ISSUE #11: Non-federated toots
This is a glitch.social feature that we can incorporate. Documentation: https://glitch-soc.github.io/docs/features/local-only-toots/

### PR DESCRIPTION
**Pull request by renatolond**
This is largely based on the glitch-soc implementation of instance-only to make it easier to incorporate back into glitch-soc.

This assumes that clients are still unaware of local-only statuses and to avoid leaking replies outside, if the local_only flag is missing, replies to local_only posts are posted as local_only.

As in the glitch-soc implementation, local_only statuses can only be seen by users that are logged in, logged out users do not see the local_only statuses in hashtag timelines or in the "take a look inside" one. local_only cannot be fetched by the other instances, even with the link. The default option is to federate the toot

* [ ]  Refactor "local_only" into something else to avoid confusion with "local", maybe "instance_only"

I originally thought about using different icons, but after discussion over at https://github.com/tootsuite/mastodon/pull/8427, it seems this would enough.

(This branch contains v2.7.2, so maybe it's better to only look at it after https://github.com/florence-social/mastodon-fork/pull/33 is merged)

This fixes https://github.com/florence-social/mastodon-fork/issues/11

image
image
image
image
image
image

### CODE REVIEW

**Comment by ghost** [comment]
Ehhh this is hard to grok with the 2.7.2 changes mixed in.  We should hurry and merge that :p

**Comment by clarfonthey** [comment]
I don't mind the mix; I just need one more reviewer to merge that. I technically could lax the restriction because I'm an admin, but out of principle I won't.

**Comment by clarfonthey** [comment]
Once #33 gets merged, would you be able to rebase these changes on top of that to avoid the merge commits? Might help a bit to read the changes.

**Comment by renatolond** [comment]
Yes, sure! I might close and reopen if I can't change the branch (this one it's in an open pr at tootsuite and I think even after the merge there will be conflicts)

**Comment by renatolond** [comment]
Closing to reopen using a branch coming from master

**Pull request closed without merging**
